#!/bin/sh
# smoke/sync-fixtures.sh — R23. Copies the fixture corpus from the gitignored
# ORIGIN into the tracked tree and REGENERATES manifest.toml with the hashes
# of what it copied.
#
# The manifest is GENERATED, never hand-edited: a hand-written hash is a hash
# that can match nothing.
#
# In E1 `wanted.txt` does not exist yet, so the loop below does not iterate
# and this run only (re)writes the header comment documenting the format —
# the machinery ships now, the data arrives with F0 of MS1.
set -eu

SRC="${1:-../sbtdd/ec-evidence}"
DST="smoke/fixtures"

test -d "$SRC" || {
  echo "FATAL: source $SRC is missing (it is gitignored, so it only exists" \
       "on a machine that captured it)"
  exit 2
}

mkdir -p "$DST"

# The header is (re)written on EVERY run, not just the first: regenerating
# the manifest must not silently drop the documentation of the format it
# produces — a manifest with only [[fixture]] blocks and no explanation of
# what "currency" or "integrity" mean is a manifest the next reader has to
# reverse-engineer.
cat > "$DST/manifest.toml" <<'HEADER'
# Fixture manifest. Generated by smoke/sync-fixtures.sh — do not hand-edit.
#
# manifest.toml — one entry PER (scenario, fixture) PAIR.
#
# A fixture used by two scenarios appears twice: same path, same hash, but its
# OWN currency line — currency is a property of WHAT IT IS USED FOR, not of
# the file. Collapsing the entries would force one currency answer for two
# questions.
#
# INTEGRITY is not CURRENCY: the hash proves the file is the one we recorded,
# NOT that the backend still answers that way. Only a live scenario proves
# currency.
#
# [[fixture]]
# scenario = "S9"                          # must be in the LIVE list of the stage
# path     = "native-E-malformed.json"
# sha256   = "<64 lowercase hex>"
# currency = "verificada-por: S9b"         # or "sin-verificar: <reason>"
HEADER

# `wanted.txt` is TRACKED and written by the task that adds fixtures — F0 of
# MS1 — one line per `<file> <scenario> <currency>`. It is the list of what
# the harness needs, and it lives in git even though the corpus does not:
# whoever clones the repo can see WHAT is missing, even before it exists.
while read -r f scenario currency; do
  [ -n "$f" ] || continue
  cp "$SRC/$f" "$DST/$f"
  # The four keys `FixtureEntry` requires. Generating an incomplete entry
  # would make the manifest fail to deserialize — and that error would
  # surface at the preflight, far from the script that produced it.
  printf '\n[[fixture]]\nscenario = "%s"\npath = "%s"\nsha256 = "%s"\ncurrency = "%s"\n' \
    "$scenario" "$f" "$(sha256sum "$DST/$f" | cut -d' ' -f1)" "$currency" \
    >> "$DST/manifest.toml"
done < "${DST}/wanted.txt" 2>/dev/null || true

echo "synced $(grep -c '^\[\[fixture\]\]' "$DST/manifest.toml" || echo 0) fixtures"
